# Generated by Django 5.0.4 on 2024-04-30 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("contact_details", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                (
                    "vendor_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
