# Generated by Django 5.0.4 on 2024-04-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_purchaseorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
