# Generated by Django 5.0.4 on 2024-04-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_purchaseorder_po_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(
                blank=True, editable=False, max_length=50, null=True, unique=True
            ),
        ),
    ]
